/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing APIMetadataType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class APIMetadataTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for APIMetadataType
        //private APIMetadataType instance;

        public APIMetadataTypeTests()
        {
            // TODO uncomment below to create an instance of APIMetadataType
            //instance = new APIMetadataType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of APIMetadataType
        /// </summary>
        [Fact]
        public void APIMetadataTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" APIMetadataType
            //Assert.IsType<APIMetadataType>(instance);
        }
    }
}
