/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing AuthenticationResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthenticationResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthenticationResults
        //private AuthenticationResults instance;

        public AuthenticationResultsTests()
        {
            // TODO uncomment below to create an instance of AuthenticationResults
            //instance = new AuthenticationResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthenticationResults
        /// </summary>
        [Fact]
        public void AuthenticationResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthenticationResults
            //Assert.IsType<AuthenticationResults>(instance);
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'LoginID'
        /// </summary>
        [Fact]
        public void LoginIDTest()
        {
            // TODO unit test for the property 'LoginID'
        }

        /// <summary>
        /// Test the property 'Sites'
        /// </summary>
        [Fact]
        public void SitesTest()
        {
            // TODO unit test for the property 'Sites'
        }

        /// <summary>
        /// Test the property 'PasswordExpired'
        /// </summary>
        [Fact]
        public void PasswordExpiredTest()
        {
            // TODO unit test for the property 'PasswordExpired'
        }
    }
}
