/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing DisableLoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisableLoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DisableLoginRequest
        //private DisableLoginRequest instance;

        public DisableLoginRequestTests()
        {
            // TODO uncomment below to create an instance of DisableLoginRequest
            //instance = new DisableLoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisableLoginRequest
        /// </summary>
        [Fact]
        public void DisableLoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DisableLoginRequest
            //Assert.IsType<DisableLoginRequest>(instance);
        }

        /// <summary>
        /// Test the property 'LoginId'
        /// </summary>
        [Fact]
        public void LoginIdTest()
        {
            // TODO unit test for the property 'LoginId'
        }
    }
}
