/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing FormsAuthenticationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FormsAuthenticationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FormsAuthenticationRequest
        //private FormsAuthenticationRequest instance;

        public FormsAuthenticationRequestTests()
        {
            // TODO uncomment below to create an instance of FormsAuthenticationRequest
            //instance = new FormsAuthenticationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FormsAuthenticationRequest
        /// </summary>
        [Fact]
        public void FormsAuthenticationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" FormsAuthenticationRequest
            //Assert.IsType<FormsAuthenticationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'BumpExisting'
        /// </summary>
        [Fact]
        public void BumpExistingTest()
        {
            // TODO unit test for the property 'BumpExisting'
        }

        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Fact]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
    }
}
