/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing GetCertificatesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCertificatesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetCertificatesRequest
        //private GetCertificatesRequest instance;

        public GetCertificatesRequestTests()
        {
            // TODO uncomment below to create an instance of GetCertificatesRequest
            //instance = new GetCertificatesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetCertificatesRequest
        /// </summary>
        [Fact]
        public void GetCertificatesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetCertificatesRequest
            //Assert.IsType<GetCertificatesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }
    }
}
