/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing GetSettingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSettingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSettingRequest
        //private GetSettingRequest instance;

        public GetSettingRequestTests()
        {
            // TODO uncomment below to create an instance of GetSettingRequest
            //instance = new GetSettingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSettingRequest
        /// </summary>
        [Fact]
        public void GetSettingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSettingRequest
            //Assert.IsType<GetSettingRequest>(instance);
        }

        /// <summary>
        /// Test the property 'SettingId'
        /// </summary>
        [Fact]
        public void SettingIdTest()
        {
            // TODO unit test for the property 'SettingId'
        }
    }
}
