/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing GetSettingsValuesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSettingsValuesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSettingsValuesRequest
        //private GetSettingsValuesRequest instance;

        public GetSettingsValuesRequestTests()
        {
            // TODO uncomment below to create an instance of GetSettingsValuesRequest
            //instance = new GetSettingsValuesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSettingsValuesRequest
        /// </summary>
        [Fact]
        public void GetSettingsValuesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSettingsValuesRequest
            //Assert.IsType<GetSettingsValuesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }

        /// <summary>
        /// Test the property 'IssuerId'
        /// </summary>
        [Fact]
        public void IssuerIdTest()
        {
            // TODO unit test for the property 'IssuerId'
        }

        /// <summary>
        /// Test the property 'LoginId'
        /// </summary>
        [Fact]
        public void LoginIdTest()
        {
            // TODO unit test for the property 'LoginId'
        }

        /// <summary>
        /// Test the property 'SettingIds'
        /// </summary>
        [Fact]
        public void SettingIdsTest()
        {
            // TODO unit test for the property 'SettingIds'
        }

        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }
    }
}
