/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing GetSiteDetailsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSiteDetailsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSiteDetailsRequest
        //private GetSiteDetailsRequest instance;

        public GetSiteDetailsRequestTests()
        {
            // TODO uncomment below to create an instance of GetSiteDetailsRequest
            //instance = new GetSiteDetailsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSiteDetailsRequest
        /// </summary>
        [Fact]
        public void GetSiteDetailsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSiteDetailsRequest
            //Assert.IsType<GetSiteDetailsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }
    }
}
