/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing PasswordComplexityRules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PasswordComplexityRulesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PasswordComplexityRules
        //private PasswordComplexityRules instance;

        public PasswordComplexityRulesTests()
        {
            // TODO uncomment below to create an instance of PasswordComplexityRules
            //instance = new PasswordComplexityRules();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PasswordComplexityRules
        /// </summary>
        [Fact]
        public void PasswordComplexityRulesInstanceTest()
        {
            // TODO uncomment below to test "IsType" PasswordComplexityRules
            //Assert.IsType<PasswordComplexityRules>(instance);
        }

        /// <summary>
        /// Test the property 'MinimumLength'
        /// </summary>
        [Fact]
        public void MinimumLengthTest()
        {
            // TODO unit test for the property 'MinimumLength'
        }

        /// <summary>
        /// Test the property 'NumChars'
        /// </summary>
        [Fact]
        public void NumCharsTest()
        {
            // TODO unit test for the property 'NumChars'
        }

        /// <summary>
        /// Test the property 'NumNumeric'
        /// </summary>
        [Fact]
        public void NumNumericTest()
        {
            // TODO unit test for the property 'NumNumeric'
        }

        /// <summary>
        /// Test the property 'NumSpecial'
        /// </summary>
        [Fact]
        public void NumSpecialTest()
        {
            // TODO unit test for the property 'NumSpecial'
        }

        /// <summary>
        /// Test the property 'RequireMixedCase'
        /// </summary>
        [Fact]
        public void RequireMixedCaseTest()
        {
            // TODO unit test for the property 'RequireMixedCase'
        }

        /// <summary>
        /// Test the property 'PasswordReuse'
        /// </summary>
        [Fact]
        public void PasswordReuseTest()
        {
            // TODO unit test for the property 'PasswordReuse'
        }
    }
}
