/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Alterian.AUTH.Model;
using Alterian.AUTH.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Alterian.AUTH.Test.Model
{
    /// <summary>
    ///  Class for testing RenameLoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenameLoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenameLoginRequest
        //private RenameLoginRequest instance;

        public RenameLoginRequestTests()
        {
            // TODO uncomment below to create an instance of RenameLoginRequest
            //instance = new RenameLoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenameLoginRequest
        /// </summary>
        [Fact]
        public void RenameLoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenameLoginRequest
            //Assert.IsType<RenameLoginRequest>(instance);
        }

        /// <summary>
        /// Test the property 'LoginId'
        /// </summary>
        [Fact]
        public void LoginIdTest()
        {
            // TODO unit test for the property 'LoginId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
