/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Alterian.AUTH.Client;
using Alterian.AUTH.Api;
// uncomment below to import models
//using Alterian.AUTH.Model;

namespace Alterian.AUTH.Test.Api
{
    /// <summary>
    ///  Class for testing CertificatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CertificatesApiTests : IDisposable
    {
        private CertificatesApi instance;

        public CertificatesApiTests()
        {
            instance = new CertificatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CertificatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CertificatesApi
            //Assert.IsType<CertificatesApi>(instance);
        }

        /// <summary>
        /// Test AddCertificate
        /// </summary>
        [Fact]
        public void AddCertificateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AddCertificateRequest addCertificateRequest = null;
            //var response = instance.AddCertificate(addCertificateRequest);
            //Assert.IsType<AddCertificateDefaultResponse>(response);
        }

        /// <summary>
        /// Test DeleteCertificate
        /// </summary>
        [Fact]
        public void DeleteCertificateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeleteCertificateRequest deleteCertificateRequest = null;
            //var response = instance.DeleteCertificate(deleteCertificateRequest);
            //Assert.IsType<LogoutDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetCertificate
        /// </summary>
        [Fact]
        public void GetCertificateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetCertificateRequest getCertificateRequest = null;
            //var response = instance.GetCertificate(getCertificateRequest);
            //Assert.IsType<GetCertificateDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetCertificates
        /// </summary>
        [Fact]
        public void GetCertificatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetCertificatesRequest getCertificatesRequest = null;
            //var response = instance.GetCertificates(getCertificatesRequest);
            //Assert.IsType<GetCertificatesDefaultResponse>(response);
        }

        /// <summary>
        /// Test UpdateCertificate
        /// </summary>
        [Fact]
        public void UpdateCertificateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateCertificateRequest updateCertificateRequest = null;
            //var response = instance.UpdateCertificate(updateCertificateRequest);
            //Assert.IsType<LogoutDefaultResponse>(response);
        }
    }
}
