/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Alterian.AUTH.Client;
using Alterian.AUTH.Api;
// uncomment below to import models
//using Alterian.AUTH.Model;

namespace Alterian.AUTH.Test.Api
{
    /// <summary>
    ///  Class for testing SitesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SitesApiTests : IDisposable
    {
        private SitesApi instance;

        public SitesApiTests()
        {
            instance = new SitesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SitesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SitesApi
            //Assert.IsType<SitesApi>(instance);
        }

        /// <summary>
        /// Test GetHostNames
        /// </summary>
        [Fact]
        public void GetHostNamesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetCertificatesRequest getCertificatesRequest = null;
            //var response = instance.GetHostNames(getCertificatesRequest);
            //Assert.IsType<GetHostNamesDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetSite
        /// </summary>
        [Fact]
        public void GetSiteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetSiteRequest getSiteRequest = null;
            //var response = instance.GetSite(getSiteRequest);
            //Assert.IsType<GetSiteDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetSiteTypes
        /// </summary>
        [Fact]
        public void GetSiteTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSiteTypes();
            //Assert.IsType<GetSiteTypesDefaultResponse>(response);
        }

        /// <summary>
        /// Test GetSites
        /// </summary>
        [Fact]
        public void GetSitesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetSitesRequest getSitesRequest = null;
            //var response = instance.GetSites(getSitesRequest);
            //Assert.IsType<GetSitesDefaultResponse>(response);
        }
    }
}
