/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.AUTH.Client.OpenAPIDateConverter;

namespace Alterian.AUTH.Model
{
    /// <summary>
    /// Certificate
    /// </summary>
    [DataContract(Name = "Certificate")]
    public partial class Certificate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Certificate" /> class.
        /// </summary>
        /// <param name="iD">Id of the certificate.</param>
        /// <param name="thumbprint">Thumbprint of the certificate, typically obtained by viewing the properties of the certificate.  The thumbprint property&#39;s hex string is placed here.             For certificates which are used as part of SAML processing, this thumbprint can be a name instead..</param>
        /// <param name="varSystem">Is this certificate a system certificate?  If you create a system certificate, you will be unable to delete it later.  This value would typically be set to false..</param>
        public Certificate(int iD = default(int), string thumbprint = default(string), bool varSystem = default(bool))
        {
            this.ID = iD;
            this.Thumbprint = thumbprint;
            this.VarSystem = varSystem;
        }

        /// <summary>
        /// Id of the certificate
        /// </summary>
        /// <value>Id of the certificate</value>
        [DataMember(Name = "ID", EmitDefaultValue = false)]
        public int ID { get; set; }

        /// <summary>
        /// Thumbprint of the certificate, typically obtained by viewing the properties of the certificate.  The thumbprint property&#39;s hex string is placed here.             For certificates which are used as part of SAML processing, this thumbprint can be a name instead.
        /// </summary>
        /// <value>Thumbprint of the certificate, typically obtained by viewing the properties of the certificate.  The thumbprint property&#39;s hex string is placed here.             For certificates which are used as part of SAML processing, this thumbprint can be a name instead.</value>
        [DataMember(Name = "Thumbprint", EmitDefaultValue = false)]
        public string Thumbprint { get; set; }

        /// <summary>
        /// Is this certificate a system certificate?  If you create a system certificate, you will be unable to delete it later.  This value would typically be set to false.
        /// </summary>
        /// <value>Is this certificate a system certificate?  If you create a system certificate, you will be unable to delete it later.  This value would typically be set to false.</value>
        [DataMember(Name = "System", EmitDefaultValue = true)]
        public bool VarSystem { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Certificate {\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  Thumbprint: ").Append(Thumbprint).Append("\n");
            sb.Append("  VarSystem: ").Append(VarSystem).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
