/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.AUTH.Client.OpenAPIDateConverter;

namespace Alterian.AUTH.Model
{
    /// <summary>
    /// RenameLoginRequest
    /// </summary>
    [DataContract(Name = "RenameLogin_request")]
    public partial class RenameLoginRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenameLoginRequest" /> class.
        /// </summary>
        /// <param name="loginId">Id of the login you wish to rename.</param>
        /// <param name="name">New login name.</param>
        public RenameLoginRequest(Guid loginId = default(Guid), string name = default(string))
        {
            this.LoginId = loginId;
            this.Name = name;
        }

        /// <summary>
        /// Id of the login you wish to rename
        /// </summary>
        /// <value>Id of the login you wish to rename</value>
        [DataMember(Name = "LoginId", EmitDefaultValue = false)]
        public Guid LoginId { get; set; }

        /// <summary>
        /// New login name
        /// </summary>
        /// <value>New login name</value>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenameLoginRequest {\n");
            sb.Append("  LoginId: ").Append(LoginId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
