/*
 * Authentication API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Alterian.AUTH.Client.OpenAPIDateConverter;

namespace Alterian.AUTH.Model
{
    /// <summary>
    /// UpdateLoginExRequest
    /// </summary>
    [DataContract(Name = "UpdateLoginEx_request")]
    public partial class UpdateLoginExRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateLoginExRequest" /> class.
        /// </summary>
        /// <param name="externalAuthentication">Should this login be exteral authenticated.</param>
        /// <param name="loginId">Id of the login.</param>
        /// <param name="name">Name of the login.</param>
        /// <param name="newPassword">If you want to reset the password, provide it here.  If ExternalAuth is true, this property is ignored..</param>
        /// <param name="settings">Settings to apply to the login.</param>
        public UpdateLoginExRequest(bool externalAuthentication = default(bool), Guid loginId = default(Guid), string name = default(string), string newPassword = default(string), List<SettingValue> settings = default(List<SettingValue>))
        {
            this.ExternalAuthentication = externalAuthentication;
            this.LoginId = loginId;
            this.Name = name;
            this.NewPassword = newPassword;
            this.Settings = settings;
        }

        /// <summary>
        /// Should this login be exteral authenticated
        /// </summary>
        /// <value>Should this login be exteral authenticated</value>
        [DataMember(Name = "ExternalAuthentication", EmitDefaultValue = true)]
        public bool ExternalAuthentication { get; set; }

        /// <summary>
        /// Id of the login
        /// </summary>
        /// <value>Id of the login</value>
        [DataMember(Name = "LoginId", EmitDefaultValue = false)]
        public Guid LoginId { get; set; }

        /// <summary>
        /// Name of the login
        /// </summary>
        /// <value>Name of the login</value>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// If you want to reset the password, provide it here.  If ExternalAuth is true, this property is ignored.
        /// </summary>
        /// <value>If you want to reset the password, provide it here.  If ExternalAuth is true, this property is ignored.</value>
        [DataMember(Name = "NewPassword", EmitDefaultValue = false)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Settings to apply to the login
        /// </summary>
        /// <value>Settings to apply to the login</value>
        [DataMember(Name = "Settings", EmitDefaultValue = false)]
        public List<SettingValue> Settings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateLoginExRequest {\n");
            sb.Append("  ExternalAuthentication: ").Append(ExternalAuthentication).Append("\n");
            sb.Append("  LoginId: ").Append(LoginId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
